---
server:
  port: 9001

spring:
  datasource:
    url: ${oauth.database.url} #your database url. Replace "xxx.x.x.x" with your ip address.
    username: ${oauth.database.username} #database schema user name
    password: ${oauth.database.password} #database schema password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
  application:
    name: amisoft-oauth-server
security:
  oauth2:
    client:
      client-id: ${oauth.client.id}
      client-secret: ${oauth.client.secret}
      authorized-grant-types: authorization_code,refresh_token,password,client_credentials
      scope: read
  user:
    role: USER
  basic:
    enabled: true

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

