---
server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/amisoft  #your database url. Replace "xxx.x.x.x" with your ip address.
    username: root #database schema user name
    password: root #database schema password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  cloud:
    consul:
      host: ${consul.host}
      port: 8500
  application:
    name: amisoft-oauth-server
security:
  oauth2:
    client:
      client-id: clientamisoft
      client-secret: clientamisoftsecret
      authorized-grant-types: authorization_code,refresh_token,password,client_credentials
      scope: read
  user:
    role: USER
  basic:
    enabled: true

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

